title: ROSを使用した画像処理とマニピュレータ制御
description: 第106回 ロボットの作り方
theme: jekyll-theme-minimal

repo: "https://github.com/gbiggs/ros_moveit_rsj_tutorial"

markdown: kramdown
highlighter: rouge

exclude:
  - README.md
  - Gemfile
